apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "xiaote.AnQuan"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 20260812
        versionName "2.26"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'org.smali:dexlib2:2.5.2'
}
